Testing TS publication

diff --git a/.github/workflows/pull-request-checks.yaml b/.github/workflows/pull-request-checks.yaml
--- a/.github/workflows/pull-request-checks.yaml
+++ b/.github/workflows/pull-request-checks.yaml
@@ -221,10 +221,22 @@ jobs:
         run: npm ci
       - name: pnpm install
         run: pnpm install -r
+      - name: Install pd cli
+        env:
+          PD_API_KEY: ${{ secrets.PD_API_KEY }}
+        run: |
+          curl -O https://cli.pipedream.com/linux/amd64/latest/pd.zip
+          unzip pd.zip
+          mkdir -p $HOME/.config/pipedream
+          echo "api_key = $PD_API_KEY" > $HOME/.config/pipedream/config
       - name: Compile TypeScript
         id: compile
         run: npm run build > files.txt
       - name: Publish TypeScript components (dry run)
+        env:
+            PD_API_KEY: ${{ secrets.PD_API_KEY }}
+            ENDPOINT: ${{ secrets.ENDPOINT }}
+        shell: bash {0} # don't fast fail
         run: |
           IFS=$'\n'
           echo "The following files will be published on merge:"
@@ -233,7 +245,49 @@ jobs:
           do
             echo "$f"
           done
+          UNPUBLISHED=""
+          PUBLISHED=""
+          ERRORS=""
+          SKIPPED=""
+          # starts with components, ends with .*js (e.g. .js and .mjs) and not app.js,
+          # doesn't end with /common*.*js, and doesn't follow */common/
+          for f in $(cat files.txt | sed 1,3d); do
+            if [[ $f == components/* ]] && [[ $f == *.*js ]] && [[ $f != *.app.*js ]] \
+              && [[ $f != */common*.*js ]] && [[ $f != */common/* ]]
+            then
+              echo "attempting to publish ${f}"
+              PD_OUTPUT=`./pd publish ${f} --json`
+              if [ $? -eq 0 ]
+              then
+                KEY=`echo $PD_OUTPUT | jq -r ".key"`
+                echo "published ${KEY}"
+                echo "${KEY} will be added to the registry"
+                curl "https://api.pipedream.com/graphql" -H "Content-Type: application/json" -H "Authorization: Bearer ${PD_API_KEY}" --data-binary $'{"query":"mutation($key: String!, $registry: Boolean!, $gitPath: String){\\n  setComponentRegistry(key: $key, registry: $registry, gitPath: $gitPath){\\n    savedComponent{\\n      id\\n      key\\n      gitPath\\n    }\\n  }\\n}","variables":{"key":"'${KEY}'","registry":'true',"gitPath":"'${f}'"}}'
+                PUBLISHED+="*${f}"
+              else
+                ERROR=`echo $PD_OUTPUT | jq -r ".error"`
+                ERROR_MESSAGE="${ERROR} with ${f}"
+                echo $ERROR_MESSAGE
+                ERRORS+="*${ERROR_MESSAGE}"
+                UNPUBLISHED+="*${f}"
+                # add to array to spit out later
+              fi
+            else
+              echo "${f} will not be added to the registry"
+              SKIPPED+="*${f}"
+            fi
+          done
+          # print out everything that didn't publish
+          if [ ${#UNPUBLISHED[@]} -ne 0 ]; then
+            echo "the following files were not published"
+            printf '%s\n' "${UNPUBLISHED[@]}"
+          fi
+          # curl with form
+          curl -X POST -d "skipped=${SKIPPED}" -d "errors=${ERRORS}" -d "unpublished=${UNPUBLISHED}" -d "published=${PUBLISHED}" $ENDPOINT
           unset IFS
+      - name: Remove pd cli config
+        run: |
+          rm $HOME/.config/pipedream/config
 
 
 
