Yet another try

diff --git a/.github/workflows/pull-request-checks.yaml b/.github/workflows/pull-request-checks.yaml
--- a/.github/workflows/pull-request-checks.yaml
+++ b/.github/workflows/pull-request-checks.yaml
@@ -46,6 +46,7 @@ jobs:
         result-encoding: string
     # Diff the changes in the HEAD ref (new branch) against the BASE ref (target branch, e.g. master)
     # If the changes don't contain modifications to the version, we want to log that fact but not exit early
+    # Once we've checked all files, exit the script if any files failed to modify version
     - id: git_diff_on_components
       name: Check git diff for version changes
       run: |-
@@ -62,8 +63,8 @@ jobs:
             echo "${{steps.base_commit.outputs.result}}"
             echo "HEAD commit: "
             echo "${{steps.head_commit.outputs.result}}"
-            git diff --unified=0 ${{steps.base_commit.outputs.result}}...${{steps.head_commit.outputs.result}} ${f} | grep 'version:'
-            if [[ $? -gt 0 ]]
+            RES=$(git diff --unified=0 ${{steps.base_commit.outputs.result}}...${{steps.head_commit.outputs.result}} ${f} | grep 'version:')
+            if [[ $? -ne 0 ]]
             then
               echo "These changes didn't modify the version of ${f}"
               commit_contained_components_that_did_not_modify_version=1
